### ISSUE TITLE
Check failed: op != nullptr Operator WarpCTC is not registered

### ISSUE THREAD

**Issue by xt479910344** [novioleo/crnn.mxnet#4]
i run the python predictor.py ,there are some errors:
[11:38:15] /home/xuting/ocr/mxnet/dmlc-core/include/dmlc/./logging.h:308: [11:38:15] src/core/op.cc:55: Check failed: op != nullptr Operator WarpCTC is not registered

Stack trace returned 10 entries:
[bt] (0) /usr/lib/python2.7/site-packages/mxnet-0.11.1-py2.7.egg/mxnet/libmxnet.so(_ZN4nnvm2Op3GetERKSs+0x329) [0x7f1833825449]
[bt] (1) /usr/lib/python2.7/site-packages/mxnet-0.11.1-py2.7.egg/mxnet/libmxnet.so(+0x28aecf8) [0x7f183380ccf8]
[bt] (2) /usr/lib/python2.7/site-packages/mxnet-0.11.1-py2.7.egg/mxnet/libmxnet.so(_ZN4dmlc20JSONObjectReadHelper13ReadAllFieldsEPNS_10JSONReaderE+0x100) [0x7f18338130a0]
[bt] (3) /usr/lib/python2.7/site-packages/mxnet-0.11.1-py2.7.egg/mxnet/libmxnet.so(+0x28adb86) [0x7f183380bb86]
[bt] (4) /usr/lib/python2.7/site-packages/mxnet-0.11.1-py2.7.egg/mxnet/libmxnet.so(_ZNSt17_Function_handlerIFN4nnvm5GraphES1_EPS2_E9_M_invokeERKSt9_Any_dataS1_+0x11f) [0x7f1832487d4f]
[bt] (5) /usr/lib/python2.7/site-packages/mxnet-0.11.1-py2.7.egg/mxnet/libmxnet.so(_ZN4nnvm11ApplyPassesENS_5GraphERKSt6vectorISsSaISsEE+0x501) [0x7f1833818a21]
[bt] (6) /usr/lib/python2.7/site-packages/mxnet-0.11.1-py2.7.egg/mxnet/libmxnet.so(_ZN5mxnet18LoadLegacyJSONPassEN4nnvm5GraphE+0x180) [0x7f1832480e60]
[bt] (7) /usr/lib/python2.7/site-packages/mxnet-0.11.1-py2.7.egg/mxnet/libmxnet.so(_ZNSt17_Function_handlerIFN4nnvm5GraphES1_EPS2_E9_M_invokeERKSt9_Any_dataS1_+0x11f) [0x7f1832487d4f]
[bt] (8) /usr/lib/python2.7/site-packages/mxnet-0.11.1-py2.7.egg/mxnet/libmxnet.so(_ZN4nnvm11ApplyPassesENS_5GraphERKSt6vectorISsSaISsEE+0x501) [0x7f1833818a21]
[bt] (9) /usr/lib/python2.7/site-packages/mxnet-0.11.1-py2.7.egg/mxnet/libmxnet.so(_ZN4nnvm9ApplyPassENS_5GraphERKSs+0x8e) [0x7f18327e7f7e]

Traceback (most recent call last):
  File "predictor.py", line 133, in <module>
    my_predictor = predict(images,(256,32),'model/digit',0,'./digit.txt',32,24,128,False)
  File "predictor.py", line 77, in __init__
    label_names=('label',)
  File "/usr/lib/python2.7/site-packages/mxnet-0.11.1-py2.7.egg/mxnet/module/module.py", line 143, in load
    sym, args, auxs = load_checkpoint(prefix, epoch)
  File "/usr/lib/python2.7/site-packages/mxnet-0.11.1-py2.7.egg/mxnet/model.py", line 394, in load_checkpoint
    symbol = sym.load('%s-symbol.json' % prefix)
  File "/usr/lib/python2.7/site-packages/mxnet-0.11.1-py2.7.egg/mxnet/symbol/symbol.py", line 1913, in load
    check_call(_LIB.MXSymbolCreateFromFile(c_str(fname), ctypes.byref(handle)))
  File "/usr/lib/python2.7/site-packages/mxnet-0.11.1-py2.7.egg/mxnet/base.py", line 143, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: Failed loading Op warpctc0 of type WarpCTC: [11:38:15] src/core/op.cc:55: Check failed: op != nullptr Operator WarpCTC is not registered

Stack trace returned 10 entries:
[bt] (0) /usr/lib/python2.7/site-packages/mxnet-0.11.1-py2.7.egg/mxnet/libmxnet.so(_ZN4nnvm2Op3GetERKSs+0x329) [0x7f1833825449]
[bt] (1) /usr/lib/python2.7/site-packages/mxnet-0.11.1-py2.7.egg/mxnet/libmxnet.so(+0x28aecf8) [0x7f183380ccf8]
[bt] (2) /usr/lib/python2.7/site-packages/mxnet-0.11.1-py2.7.egg/mxnet/libmxnet.so(_ZN4dmlc20JSONObjectReadHelper13ReadAllFieldsEPNS_10JSONReaderE+0x100) [0x7f18338130a0]
[bt] (3) /usr/lib/python2.7/site-packages/mxnet-0.11.1-py2.7.egg/mxnet/libmxnet.so(+0x28adb86) [0x7f183380bb86]
[bt] (4) /usr/lib/python2.7/site-packages/mxnet-0.11.1-py2.7.egg/mxnet/libmxnet.so(_ZNSt17_Function_handlerIFN4nnvm5GraphES1_EPS2_E9_M_invokeERKSt9_Any_dataS1_+0x11f) [0x7f1832487d4f]
[bt] (5) /usr/lib/python2.7/site-packages/mxnet-0.11.1-py2.7.egg/mxnet/libmxnet.so(_ZN4nnvm11ApplyPassesENS_5GraphERKSt6vectorISsSaISsEE+0x501) [0x7f1833818a21]
[bt] (6) /usr/lib/python2.7/site-packages/mxnet-0.11.1-py2.7.egg/mxnet/libmxnet.so(_ZN5mxnet18LoadLegacyJSONPassEN4nnvm5GraphE+0x180) [0x7f1832480e60]
[bt] (7) /usr/lib/python2.7/site-packages/mxnet-0.11.1-py2.7.egg/mxnet/libmxnet.so(_ZNSt17_Function_handlerIFN4nnvm5GraphES1_EPS2_E9_M_invokeERKSt9_Any_dataS1_+0x11f) [0x7f1832487d4f]
[bt] (8) /usr/lib/python2.7/site-packages/mxnet-0.11.1-py2.7.egg/mxnet/libmxnet.so(_ZN4nnvm11ApplyPassesENS_5GraphERKSt6vectorISsSaISsEE+0x501) [0x7f1833818a21]
[bt] (9) /usr/lib/python2.7/site-packages/mxnet-0.11.1-py2.7.egg/mxnet/libmxnet.so(_ZN4nnvm9ApplyPassENS_5GraphERKSs+0x8e) [0x7f18327e7f7e]

**Comment by novioleo** [comment]
your mxnet DON'T COMPILED FROM SOURCE AND NOT BIND WITH WARPCTC
this ref will help you out
https://github.com/apache/incubator-mxnet/tree/master/example/warpctc

**Comment by kli-nlpr** [comment]
The link https://github.com/apache/incubator-mxnet/tree/master/example/warpctc  is dead?

**Comment by novioleo** [comment]
@kli-nlpr updated。

**Comment by kli-nlpr** [comment]
@novioleo  用MXNet自带的ctc是否可以呢？  http://mxnet.incubator.apache.org/api/python/symbol/contrib.html#mxnet.symbol.contrib.CTCLoss

**Comment by novioleo** [comment]
@kli-nlpr 可以是可以，但是呢，我觉得效果没有warpctc好。而且我们很多时候框架在换，但是ctc不想换。

**Comment by kli-nlpr** [comment]
我将Warpctc
```
 label = mx.sym.Reshape(data=label, shape=(-1,))
 label = mx.sym.Cast(data=label, dtype='int32')
 sm = mx.sym.WarpCTC(data=pred, label=label, label_length=num_label, input_length=seq_len)
```

改为
```

    pred_ctc = mx.sym.Reshape(data=pred, shape=(-4, seq_len, -1, 0))
    loss = mx.sym.contrib.CTCLoss(data=pred_ctc, label=label)
    ctc_loss = mx.sym.MakeLoss(loss)
    return ctc_loss
```
训练报错。

```
../tensor/broadcast_reduce_op.h:121: Check failed: axis < ndim && axis >= -ndim axis 1 exceeds the input dimension of 1
```
是哪里用错了吗。

**Comment by novioleo** [comment]
ctc loss的输入我不了解。
所以，我不能给你提供什么帮助。你可以自己去了解下。

**Comment by kli-nlpr** [comment]
如果我只想做预测，是否可以用不带warpctc的mxnet来做？
具体该怎么做呢？
谢谢！

**Comment by novioleo** [comment]
如果只是预测的话是不需要的。我在我的predict里面就没用～
